import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/About.module.css";
import AboutCard from "../components/AboutCard";
import Community from "../components/Community";
import Team from "../components/Team";
import Footer from "../components/footer";

const reasons = [
  {
    color: "rgba(0, 0, 255, 0.596)",
    title: "Reason 1",
    info: "Lorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
  {
    color: "orange",
    title: "Reason 2",
    info: "Lorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
  {
    color: "teal",
    title: "Reason 3",
    info: "Lorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
  {
    color: "rgba(255, 0, 0, 0.699)",
    title: "Reason 4",
    info: "Lorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
];

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/EgyomLogo.svg" />
      </Head>

      <main style={{ marginBottom: "50px" }}>
        <section className={styles.heroContainer}>
          <div className={styles.heroTitle}>
            <h2>About Us</h2>
          </div>
          <div className={styles.heroText}>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Odio
              lobortis nisl blandit cras eu nunc massa imperdiet tincidunt. Cras
              dui non tincidunt fermentum tortor vel morbi eget vehicula. Diam
              ultrices mattis sem tincidunt sit ut velit sit.
              <br />
              <br />
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Odio
              lobortis nisl blandit cras eu nunc massa imperdiet tincidunt. Cras
              dui non tincidunt fermentum tortor vel morbi eget vehicula. Diam
              ultrices mattis sem tincidunt sit ut velit sit.
            </p>
          </div>
        </section>
        <div className={styles.heroImageContent}></div>
        <div className={styles.heroSubtitle}>
          <h2>
            “It is our mission to lorem ipsum dolor sit amet, consectetur
            adipiscing elit.”
          </h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem
            rhoncus sodales magna tellus est lectus. Id et bibendum eget
            suspendisse phasellus tristique. Amet aliquet morbi purus integer
            sit integer sagittis nunc.
          </p>
        </div>
        <section className={styles.reasons}>
          <div className={styles.reasonsText}>
            <h2>Why Egyom</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem
              rhoncus sodales magna tellus est lectus. Id et bibendum eget
            </p>
            <button className={styles.joinButton}>Join Egyom</button>
          </div>
          <div className={styles.reasonsCrads}>
            <div className={styles.AboutCardContainer}>
              {reasons.map((item, index) => (
                <AboutCard
                  key={index}
                  color={item.color}
                  title={item.title}
                  info={item.info}
                />
              ))}
            </div>
          </div>
        </section>
        <h6 className={styles.headerTitle}>Meet the Team</h6>
        <h4 className={styles.headerSubTitle}>The faces behid Egyom</h4>
        <Team />
        <Community />
        <Footer />
      </main>
    </div>
  );
};

export default About;
