import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Contact.module.css";
import ContactHeadlineImage from "../public/images/ContactHeadlineImage.svg";
import ClientsProfessionals from "../components/ClientsProfessionals";
import Community from "../components/Community";
import ContactForms from "../components/ContactForms";
import Footer from "../components/footer";

const Contact: NextPage = () => {
  const [searchOption, setSearchOption] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/EgyomLogo.svg" />
      </Head>
      <main>
        <div className={styles.heroContainer}>
          <div style={{ flex: 2 }}>
            <div>
              <h1 className={styles.heroHeading}>Need our help? Talk to us</h1>
              <p style={{ fontSize: "20px" }}>
                Contact us when you have any lorem ipsum dolor sit amet,
                consectetur adipiscing elit. Velit mauris urna nunc quisque
                netus
              </p>
            </div>
            <button className={styles.heroButton1}>Live Chat</button>
          </div>
          <div className={styles.heroImage}>
            <Image
              unoptimized
              src={ContactHeadlineImage}
              alt="hero image"
              width={700}
              height={700}
            />
          </div>
        </div>
        <div>
          <ContactForms />
        </div>
        <Community />
        <Footer />
      </main>
    </div>
  );
};

export default Contact;
