import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/FAQS.module.css";
import Community from "../components/Community";
import FAQS from "../components/FAQS";
import Footer from "../components/footer";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>FAQS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/EgyomLogo.svg" />
      </Head>

      <main style={{ marginBottom: "50px" }}>
        <section className={styles.headingContainer}>
          <p className={styles.heading1}>FAQS</p>
          <b className={styles.heading2}>Find the answers</b>
          <p className={styles.headingText}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ultrices a
            maecenas sit vivamus nulla. In amet tristique ipsum volutpat eu.
          </p>
        </section>
        <div className={styles.heroImageContent}></div>
        <section className={styles.faqsContainer}>
          <div className={styles.buttonAndTextContainer}>
            <div>
              <p>
                Can’t find what you are looking for? <br /> orem ipsum dolor sit
                amet, consectetur adipiscing.
              </p>
            </div>
            <div className={styles.buttonContainer}>
              <button className={styles.faqsWorksButton}>How it Works</button>
              <button className={styles.faqsContactButton}>Contact Us</button>
            </div>
          </div>
          <div className={styles.faqsSelectContainer}>
            <h2>
              <FAQS />
            </h2>
          </div>
        </section>

        <Community />
        <Footer />
      </main>
    </div>
  );
};

export default About;
