import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HomeImage from "../public/images/HomeHeadlineimage.svg";
import HomepageCategories from "../components/HomepageCategories";
import HireCard from "../components/HireCard";
import Community from "../components/Community";
import ClientsProfessionals from "../components/ClientsProfessionals";
import Footer from "../components/footer";

interface Details {
  name: string;
  image: string;
  description: string;
  rating: number;
  reviews: number;
  amount: number;
  profilePic: string;
  certified?: boolean;
  skills: string[];
}

const data: Details[] = [
  {
    name: "James Doe",
    image: "/images/h1.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 222,
    amount: 180,
    certified: true,
    profilePic: "/images/pc1.webp",
    skills: ["React", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/h2.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 210,
    amount: 1080,
    certified: true,
    profilePic: "/images/Ellipse3.svg",
    skills: ["React", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/h4.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 250,
    certified: false,
    profilePic: "/images/pc1.webp",
    skills: ["React", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/h3.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 10,
    amount: 100,
    certified: true,
    profilePic: "/images/pc3.jpg",
    skills: ["React", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/h1.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 100,
    certified: false,
    profilePic: "/images/h1.jpg",
    skills: ["React", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/h2.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 100,
    certified: true,
    profilePic: "/images/pc5.jpg",
    skills: ["React", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/h3.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 100,
    certified: true,
    profilePic: "/images/pc6.jpg",
    skills: ["React", "Node", "Illustrator"],
  },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Egyom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/EgyomLogo.svg" />
      </Head>

      <main>
        <div className={styles.homepageHeroContainer}>
          <div style={{ flex: 3 }}>
            <div>
              <h1 className={styles.homepageHeroHeading}>
                Discover jobs and find talents.
              </h1>
              <p className={styles.heroText}>
                If you are looking for a job or a f reelancer to turn your next{" "}
                idea into a real product, we’ve got you covered.
              </p>
            </div>
            <div className={styles.buttonContainer}>
              <button className={styles.homepageHeroButton1}>Join Egyom</button>
              <button className={styles.homepageHeroButton2}>
                How it works
              </button>
            </div>
          </div>
          <div style={{ flex: 2, alignItems: "end" }}>
            <Image
              className={styles.homepageHeroImage}
              unoptimized
              src={HomeImage}
              alt="hero image"
              width={700}
              height={700}
            />
          </div>
        </div>

        <div className={styles.homepageCatergoryContainer}>
          <section className={styles.sectioncatSub}>
            <h6>Top Categories</h6>
            <h4>Find and work with talented freelancers</h4>
          </section>
          <HomepageCategories />

          <section className={styles.homepageCatergoryButtonTitle}>
            <h6 style={{ color: "#808080" }}>
              Can’t find what you’re looking for?
            </h6>
            <button className={styles.homepageCatergoryButton}>
              View all Services
            </button>
          </section>
        </div>
        <div className={styles.getStartedContainer}>
          <section>
            <h4>Get Started</h4>
            <h2>How Egyom Works</h2>
          </section>
          <ClientsProfessionals />

          <section className={styles.homepageCatergoryButtonContainer}>
            <h6>Create an account from the comfort of your home</h6>
            <button className={styles.homepageCatergoryButton}>
              Join Egyom
            </button>
          </section>
          <section className={styles.professional}>
            <div className={styles.findAndHire}>
              <h6 style={{ color: "#808080" }}>Hire</h6>
              <h4>Professional Services</h4>
            </div>

            <HireCard data={data} />
            <section>
              <h6>Can’t find what you’re looking for?</h6>
              <button className={styles.homepageCatergoryButton}>
                View all Services
              </button>
            </section>
          </section>
          <Community />
        </div>
        <Footer />
      </main>
    </div>
  );
};

export default Home;
