import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/About.module.css";
import Community from "../components/Community";
import Footer from "../components/footer";
import { style } from "@mui/system";

interface data {
  title: string;
  info: string;
}

const termsData: data[] = [
  {
    title: "Some Headline",
    info: "Lorem ipsum ctosuscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto  suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaqueLorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
  {
    title: "Some Headline",
    info: "Lorem ipsum cto cto suscipit sunt iste velit fuga isuscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto n harum ducimus hic. Magni adipiscisuscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaqueLorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
  {
    title: "Some Headline",
    info: "Lorem ipsum ctocto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci sususcipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto scipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaqueLorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
  {
    title: "Some Headline",
    info: "Lorem ipsum cto suscipit cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscisunt iste velit fuga in harum ducimsuscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto us hic. Magni adipisci amet ex ut eaqueLorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
];
const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/EgyomLogo.svg" />
      </Head>

      <main style={{ marginBottom: "50px" }}>
        <div className={styles.termsContainer}>
          <section>
            <h4>Updated 22 February 2022</h4>
            <h2>Privacy Policy</h2>
          </section>

          <section>
            {termsData.map((item, index) => (
              <div key={index}>
                <h3 style={{ display: "flex", alignItems: "center" }}>
                  <div className={styles.policyDot}></div> {item.title}
                </h3>
                <p>{item.info}</p>
              </div>
            ))}
          </section>
        </div>
        <Community />
        <Footer />
      </main>
    </div>
  );
};

export default About;
