import React, { useState } from "react";
import type { NextPage } from "next";
import Select from "react-select";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Professionals.module.css";
import HomeImage from "../public/images/ProfessionalsHeadlineImage.svg";
import ProfessionalsCard from "../components/ProfessionalsCard";
import Community from "../components/Community";
import Footer from "../components/footer";
import Pagination from "../components/Pagination";

const colourOptions = [
  { value: "ocean1", label: "Ocean" },
  { value: "blue", label: "Blue" },
  { value: "purple", label: "Purple" },
  { value: "red", label: "Red" },
  { value: "orange", label: "Orange" },
  { value: "yellow", label: "Yellow" },
  { value: "green", label: "Green" },
  { value: "forest", label: "Forest" },
  { value: "slate", label: "Slate" },
  { value: "silver", label: "Silver" },
];

interface Details {
  name: string;
  image: string;
  description: string;
  rating: number;
  reviews: number;
  amount: number;
  profilePic: string;
  certified?: boolean;
  skills: string[];
}

const data: Details[] = [
  {
    name: "James Doe",
    image: "/images/Ellipse1.svg",
    description:
      "Lorem ipsum dolor sit amet,ipsum ipsum dolor sit ametLorem  um dolor sit amet,ipsum ipsum dolor sit ametLoripsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 222,
    amount: 180,
    certified: true,
    profilePic: "/images/pc1.webp",
    skills: ["Vue", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/Ellipse2.svg",
    description:
      "Lorem ipsum dolorLorem isit ametLorem   ipsum dolor sit ametLoripsum dolor sit amet,Lorem ipsum dolor dolor sit amet sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 210,
    amount: 1080,
    certified: true,
    profilePic: "/images/Ellipse3.svg",
    skills: ["React", "Node"],
  },
  {
    name: "Jame Doe",
    image: "/images/Ellipse4.svg",
    description:
      "Lorem ipsum dolor sit amet,LLorem ipsum dolor sit amet,Loreipsum dolor sit amet,Lorem ipm ipipsum dolor the greate guy",
    rating: 5.0,
    reviews: 2,
    amount: 250,
    certified: false,
    profilePic: "/images/pc1.webp",
    skills: ["Angular", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/Ellipse5.svg",
    description:
      "Lorem ipsum dolor sit amet,LLorem ipsum dolor sit amet,Lorem ipsipsum dolor sit amet,Lorem ipum dolor sit ametorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 10,
    amount: 100,
    certified: true,
    profilePic: "/images/pc3.jpg",
    skills: ["React", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/Ellipse6.svg",
    description:
      "Lorem ipsum dolor sit amet,Lorem iLorem ipsum dolor ipsum dolor sit amet,Lorem ipsit amet,Lorem ipsum dolor sit ametpsum dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 100,
    certified: false,
    profilePic: "/images/pc4.jpg",
    skills: ["React", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/Ellipse7.svg",
    description:
      "Lorem ipsum dolor sit amet,Lorem ipsLorem ipsum dolor siipsum dolor sit amet,Lorem ipt amet,Lorem ipsum dolor sit ametum dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 100,
    certified: true,
    profilePic: "/images/pc5.jpg",
    skills: ["React", "Node", "Illustrator"],
  },
  {
    name: "Jame Doe",
    image: "/images/Ellipse8.svg",
    description:
      "Lorem ipsum dolor sit amet,Lorem ipsumLorem ipsum dolor sit amet,Lorem ipsum dolor sit amet dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 100,
    certified: true,
    profilePic: "/images/pc6.jpg",
    skills: ["React", "Node", "Illustrator"],
  },
];

const Professionals: NextPage = (props) => {
  const [searchOption, setSearchOption] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Professionals</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/EgyomLogo.svg" />
      </Head>

      <main>
        <div className={styles.heroContainer}>
          <div style={{ flex: 2 }}>
            <div>
              <h1 className={styles.heroHeading}>
                Your talent search begins here
              </h1>
              <p style={{ fontSize: "20px" }}>
                Find a selection of freelance Professionals lorem ipsum dolor
                sit amet, consectetur adipiscing elit. Velit mauris urna nunc
                quisque netus.
              </p>
            </div>
          </div>
          <div
            className={styles.heroImage}
            style={{ flex: 3, alignItems: "end" }}
          >
            <Image
              unoptimized
              src={HomeImage}
              alt="hero image"
              width={700}
              height={700}
            />
          </div>
        </div>
        <div className={styles.searhContainer}>
          <input type="text" placeholder="Search by name or skill" />
          <button>Search</button>
        </div>
        <div className={styles.categoryContainer}>
          <div className={styles.categorySettingsContainer}>
            <h6>Search Settings</h6>

            <form className={styles.searchForm} onSubmit={() => {}}>
              <label htmlFor="">Sort by</label>
              <select
                value={searchOption}
                onChange={(e) => setSearchOption(e.target.value)}
              >
                <option value="grapefruit">Grapefruit</option>
                <option value="lime">Lime</option>
                <option value="coconut">Coconut</option>
                <option value="mango">Mango</option>
              </select>
              <label htmlFor="">Skills</label>
              <select
                value={searchOption}
                onChange={(e) => setSearchOption(e.target.value)}
              >
                <option value="grapefruit">Grapefruit</option>
                <option value="lime">Lime</option>
                <option value="coconut">Coconut</option>
                <option value="mango">Mango</option>
              </select>

              <button type="submit" className={styles.searchSettingsButton1}>
                Apply Filter
              </button>
            </form>
          </div>
          <div className={styles.categoryProfessionalsContainer}>
            <div className={styles.categoryProfessionalsHeaderContainer}>
              <div className={styles.categoryProfessionalsHeaderResults}>
                1000 Professionals Found
              </div>
            </div>
            <ProfessionalsCard data={data} />

            <Pagination />
          </div>
        </div>
        <Community />
        <Footer />
      </main>
    </div>
  );
};

export default Professionals;
