import React, { useState } from "react";
import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import StarIcon from "@mui/icons-material/Star";
import IconButton, { IconButtonProps } from "@mui/material/IconButton";
import styles from "../styles/ServiceDetails.module.css";
import Community from "../components/Community";
import Footer from "../components/footer";
import ProfileInfoCard from "../components/ProfileInfoCard";
import { ServiceDetailsModal } from "../components/ServiceDetailsModal";
import Pagination from "../components/Pagination";
import SkillTag from "../components/SkillTag";
import { useRouter } from "next/router";

interface Details {
  name: string;
  image: string;
  description: string;
  rating: number;
  reviews: number;
  amount: number;
  profilePic: string;
  bookMark?: boolean;
}

const data: Details[] = [
  {
    name: "Jame Doe",
    image: "/images/h1.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 100,
    profilePic: "/images/Ellipse5.svg",
    bookMark: true,
  },
  {
    name: "Jame Doe",
    image: "/images/h2.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 100,
    profilePic: "/images/Ellipse5.svg",
    bookMark: true,
  },
  {
    name: "Jame Doe",
    image: "/images/h3.jpg",
    description: "Lorem ipsum dolor sit amet,Lorem ipsum dolor sit amet,",
    rating: 5.0,
    reviews: 2,
    amount: 100,
    profilePic: "/images/Ellipse5.svg",
  },
];

const ProfileInformation: NextPage = () => {
  const [searchOption, setSearchOption] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Services Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/EgyomLogo.svg" />
      </Head>

      <main>
        <div className={styles.servicessSummary}>
          <section className={styles.categoryContainer}>
            <div className={styles.categorySettingsContainer}>
              <ProfileInfoCard />
            </div>
            <div className={styles.categoryServicesContainer}>
              <ServiceDetailsModal data={data} />
              <div>
                <h2>Reviews (3)</h2>
              </div>
              <div className={styles.details}>
                <div className={`${styles.reviewContent}`}>
                  <div>
                    <div style={{ display: "flex", alignItems: "center" }}>
                      Seller Reviews (19)
                      <span
                        style={{
                          display: "flex",
                          alignItems: "center",
                          color: "orange",
                          fontSize: 16,
                        }}
                      >
                        <StarIcon sx={{ fontSize: 16 }} />
                        <StarIcon sx={{ fontSize: 16 }} />
                        <StarIcon sx={{ fontSize: 16 }} />
                        <StarIcon sx={{ fontSize: 16 }} />
                        <StarIcon sx={{ fontSize: 16 }} />
                        5.0
                      </span>
                    </div>
                  </div>
                  <button>Rate Seller</button>
                </div>
                <div className={styles.commentsContainer}>
                  <div className={styles.commentsPic}>
                    <Image
                      className={styles.commentProfileImage}
                      unoptimized
                      src="./images/pc1.webp"
                      alt="hero image"
                      width={80}
                      height={80}
                    />
                  </div>
                  <div className={styles.commentsCommen}>
                    <div className={styles.commentNameRating}>
                      <b>Buyer Name</b>
                      <span
                        style={{
                          color: "orange",
                          fontWeight: "600",
                          display: "flex",
                          alignItems: "center",
                        }}
                      >
                        <StarIcon sx={{ color: "orange", fontSize: 16 }} />
                        <span>5.0</span>
                      </span>
                    </div>
                    <div className={styles.buyerComment}>
                      <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Exercitationem recusandae non accusantium, illo error,
                        blanditiis inventore, necessitatibus quibusdam fugit
                        minus sit maxime sapiente autem quo ratione architecto
                        quam magnam consequuntur? blanditiis inventore,
                        necessitatibus quibusdam fugit minus sit maxime sapiente
                        autem quo ratione architecto quam magnam consequuntur?
                      </p>
                    </div>
                    <div className={styles.commentsDuration}>2 weeks ago</div>
                  </div>
                </div>
                <div className={styles.commentsContainer}>
                  <div className={styles.commentsPic}>
                    <Image
                      className={styles.commentProfileImage}
                      unoptimized
                      src="./images/pc1.webp"
                      alt="hero image"
                      width={80}
                      height={80}
                    />
                  </div>
                  <div className={styles.commentsCommen}>
                    <div className={styles.commentNameRating}>
                      <b>Buyer Name</b>
                      <span
                        style={{
                          color: "orange",
                          fontWeight: "600",
                          display: "flex",
                          alignItems: "center",
                        }}
                      >
                        <StarIcon sx={{ color: "orange", fontSize: 16 }} />
                        <span>5.0</span>
                      </span>
                    </div>
                    <div className={styles.buyerComment}>
                      <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Exercitationem recusandae non accusantium, illo error,
                        blanditiis inventore, necessitatibus quibusdam fugit
                        minus sit maxime sapiente autem quo ratione architecto
                        quam magnam consequuntur? blanditiis inventore,
                        necessitatibus quibusdam fugit minus sit maxime sapiente
                        autem quo ratione architecto quam magnam consequuntur?
                      </p>
                    </div>
                    <div className={styles.commentsDuration}>2 weeks ago</div>
                  </div>
                </div>
                <div className={styles.commentsContainer}>
                  <div className={styles.commentsPic}>
                    <Image
                      className={styles.commentProfileImage}
                      unoptimized
                      src="./images/pc1.webp"
                      alt="hero image"
                      width={80}
                      height={80}
                    />
                  </div>
                  <div className={styles.commentsCommen}>
                    <div className={styles.commentNameRating}>
                      <b>Buyer Name</b>
                      <span
                        style={{
                          color: "orange",
                          fontWeight: "600",
                          display: "flex",
                          alignItems: "center",
                        }}
                      >
                        <StarIcon sx={{ color: "orange", fontSize: 16 }} />
                        <span>5.0</span>
                      </span>
                    </div>
                    <div className={styles.buyerComment}>
                      <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Exercitationem recusandae non accusantium, illo error,
                        blanditiis inventore, necessitatibus quibusdam fugit
                        minus sit maxime sapiente autem quo ratione architecto
                        quam magnam consequuntur? blanditiis inventore,
                        necessitatibus quibusdam fugit minus sit maxime sapiente
                        autem quo ratione architecto quam magnam consequuntur?
                      </p>
                    </div>
                    <div className={styles.commentsDuration}>2 weeks ago</div>
                  </div>
                </div>
                {/* pagination */}
                <Pagination />
              </div>
            </div>
          </section>
        </div>
        <div className={styles.servicessSummaryMobile}>
          <div className={styles.categorySettingsContainer}>
            <ProfileInfoCard />
          </div>
        </div>
        <Community />
        <Footer />
      </main>
    </div>
  );
};

export default ProfileInformation;
