import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/About.module.css";
import Community from "../components/Community";
import Footer from "../components/footer";

interface data {
  title: string;
  info: string;
}

const termsData: data[] = [
  {
    title: "a. Header",
    info: "Lorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaqueLorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hicsuscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto . Magni adipisci amet ex ut eaque.",
  },
  {
    title: "b. Header",
    info: "Lorem ipsum cto cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscisuscipit sususcipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto nt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaqueLorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
  {
    title: "c. Header",
    info: "Lorem ipsum ctocto suscipit sunt iste vesuscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto lit fuga in harum ducimus hic. Magni adipisci suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaqueLorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
  {
    title: "d. Header",
    info: "Lorem ipsum cto suscipit cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscisunt iste velit fuga in harum ducimus hic. Magni adipisci asuscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipiscicto met ex ut eaqueLorem ipsum cto suscipit sunt iste velit fuga in harum ducimus hic. Magni adipisci amet ex ut eaque.",
  },
];
const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Terms of Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/EgyomLogo.svg" />
      </Head>

      <main style={{ marginBottom: "50px" }}>
        <div className={styles.termsContainer}>
          <section>
            <h4>Agreement</h4>
            <h2>Terms of Service</h2>
          </section>

          <section>
            {termsData.map((item, index) => (
              <div key={index}>
                <h3>{item.title}</h3>
                <p>{item.info}</p>
              </div>
            ))}
          </section>
        </div>
        <Community />
        <Footer />
      </main>
    </div>
  );
};

export default About;
